# Generated by Django 2.2.7 on 2019-11-14 00:13

from django.conf import settings
from django.db import migrations, models

import cards.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_name', models.CharField(max_length=50)),
                ('ingredients', models.TextField()),
                ('safety', models.TextField()),
                ('meal_url', models.URLField()),
                ('image', models.ImageField(default='static/images/default_meal_small.jpg', upload_to='')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=models.SET(cards.models.get_admin_user), to=settings.AUTH_USER_MODEL)),
                ('collectors', models.ManyToManyField(blank=True, related_name='meals_collected', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
