# Generated by Django 2.2.7 on 2019-11-16 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_auto_20191116_0116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='meal_url',
            field=models.URLField(blank=True),
        ),
    ]
