# Generated by Django 2.2.7 on 2019-11-16 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_auto_20191116_0334'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meal',
            old_name='image',
            new_name='image_file',
        ),
        migrations.AddField(
            model_name='meal',
            name='image_url',
            field=models.TextField(blank=True),
        ),
    ]
