# Generated by Django 2.2.7 on 2019-11-20 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0008_meal_results'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='image_file',
            field=models.ImageField(default='default_meal_small.jpg', upload_to='meals_images'),
        ),
    ]
