# Generated by Django 2.2.7 on 2019-11-20 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0009_auto_20191120_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='image_file',
            field=models.ImageField(default='default_big.jpg', upload_to='meals_images'),
        ),
    ]
