# Generated by Django 2.2.7 on 2019-11-20 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0010_auto_20191120_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='image_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
