# Generated by Django 2.2.7 on 2019-11-21 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0011_auto_20191120_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='safety',
            field=models.TextField(blank=True),
        ),
    ]
