# Generated by Django 2.2.7 on 2019-11-21 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0012_auto_20191121_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='image_file',
            field=models.ImageField(blank=True, default='default_big.jpg', upload_to='meals_images'),
        ),
    ]
