# Generated by Django 2.2.7 on 2019-11-26 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0013_auto_20191121_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='tokens',
            field=models.TextField(blank=True),
        ),
    ]
